/**
 * BattleCard — represents a single tabletop battle generated by an attack in the app.
 * Stored as a Base44 entity. One attack → one BattleCard.
 *
 * Battle scaling:
 *   tabletop_points = round((attacker_troops + defender_troops) * scale_factor * avg_battle_points)
 *   Clamped to [minBattlePoints, maxBattlePoints] from config.
 *   After the tabletop game: surviving_troops → app troop loss via reverse scaling.
 *   scale_factor and avg_battle_points come from the campaign's TabletopGameProfile.
 */
export type BattleCardType =
  | 'skirmish'
  | 'siege'
  | 'double_siege'
  | 'capture_objective'
  | 'bloodbath';

export type BattleCardStatus =
  | 'generated'
  | 'awaiting_play'
  | 'result_submitted'
  | 'awaiting_approval'
  | 'resolved'
  | 'delayed'
  | 'auto_resolved'
  | 'forfeited';

export interface BattleCard {
  id: string;
  campaign_id: string;
  /** CampaignPlayer ID of the attacking player */
  attacker_player_id: string;
  /** CampaignPlayer ID of the defending player */
  defender_player_id: string;
  /** Territory being contested */
  territory_id: string;
  /** Round in which this battle was generated */
  round: number;
  /** Battle type determines scenario rules in the tabletop game */
  type: BattleCardType;
  status: BattleCardStatus;
  /** Tabletop points size for this battle (scaled from app troop counts) */
  scaled_points: number;
  /** App-side troop counts at the time of battle generation */
  attacker_troops_at_battle: number;
  defender_troops_at_battle: number;
  /** ISO deadline for auto-resolution */
  resolve_by?: string;
  created_date?: string;
  updated_date?: string;
}

/**
 * BattleResultSubmission — submitted outcome of a played BattleCard.
 * Stored as a Base44 entity. Requires approval from the opposing player.
 */
export interface BattleResultSubmission {
  id: string;
  battle_card_id: string;
  /** CampaignPlayer ID of the submitter */
  submitted_by_player_id: string;
  /** CampaignPlayer ID of the winning player */
  winner_player_id: string;
  /** Surviving tabletop troops (used for reverse scaling to app troop losses) */
  attacker_surviving_troops: number;
  defender_surviving_troops: number;
  /** Optional notes / context */
  notes?: string;
  /** Whether the opposing player has approved this submission */
  is_approved: boolean;
  created_date?: string;
  updated_date?: string;
}