/**
 * BattleCard — represents a tabletop battle generated from one or more attacks or operations.
 *
 * v1 12-card battle library:
 *
 * MILITARY (generated by attack phase):
 *   bloodbath:           mutual attacks between the same two territories — ONE card, no single defender
 *   skirmish:            1 attacker, target neutral/vacated → auto-resolve, no card created
 *   capture_objectives:  2+ attackers, target neutral/vacated → tabletop resolution required
 *   siege:               1 attacker, target has a live defender
 *   double_siege:        2+ attackers, target has a live defender
 *
 * ECONOMIC (generated by Operations Phase):
 *   supply_route_establishment  — contest activation of a new supply route
 *   supply_route_race           — challenge ownership of an existing supply route
 *   supply_raid                 — steal stored resources from enemy territory
 *   supply_caravan_escort       — protect or intercept a resource shipment
 *
 * DIPLOMATIC (generated by Operations Phase):
 *   uprising            — garrison reduction via civil unrest
 *   labor_strike        — resource destruction at a hub territory
 *   tax_protest         — gold seizure challenge
 *   manufactured_crisis — peacekeeping / diplomat influence play
 *
 * Battle scaling (military types):
 *   scale_factor  = total_troops_in_battle / avg_battle_size  (min 1.0)
 *   tabletop_size = round(total_troops_in_battle / scale_factor)
 */

// ─── Battle pillar ────────────────────────────────────────────────────────────

export type BattleCardPillar = 'military' | 'economic' | 'diplomatic';

// ─── Battle types ─────────────────────────────────────────────────────────────

export type MilitaryBattleType =
  | 'skirmish'           // auto-resolved, no card; included for completeness
  | 'siege'              // 1 attacker vs defender
  | 'double_siege'       // 2+ attackers vs defender
  | 'capture_objectives' // 2+ attackers vs neutral/vacated territory
  | 'bloodbath';         // mutual attack pair — one card, no single defender

export type EconomicBattleType =
  | 'supply_route_establishment'
  | 'supply_route_race'
  | 'supply_raid'
  | 'supply_caravan_escort';

export type DiplomaticBattleType =
  | 'uprising'
  | 'labor_strike'
  | 'tax_protest'
  | 'manufactured_crisis';

/** All 12 canonical v1 battle types. */
export type BattleCardType = MilitaryBattleType | EconomicBattleType | DiplomaticBattleType;

// ─── Pillar lookup map ────────────────────────────────────────────────────────

export const BATTLE_TYPE_PILLAR: Record<BattleCardType, BattleCardPillar> = {
  // Military
  skirmish:            'military',
  siege:               'military',
  double_siege:        'military',
  capture_objectives:  'military',
  bloodbath:           'military',
  // Economic
  supply_route_establishment: 'economic',
  supply_route_race:          'economic',
  supply_raid:                'economic',
  supply_caravan_escort:      'economic',
  // Diplomatic
  uprising:           'diplomatic',
  labor_strike:       'diplomatic',
  tax_protest:        'diplomatic',
  manufactured_crisis:'diplomatic',
};

// ─── Display labels ───────────────────────────────────────────────────────────

export const BATTLE_TYPE_LABELS: Record<BattleCardType, string> = {
  skirmish:            'Skirmish',
  siege:               'Siege',
  double_siege:        'Double Siege',
  capture_objectives:  'Capture Objectives',
  bloodbath:           'Bloodbath',
  supply_route_establishment: 'Route Establishment',
  supply_route_race:          'Route Race',
  supply_raid:                'Supply Raid',
  supply_caravan_escort:      'Caravan Escort',
  uprising:            'Uprising',
  labor_strike:        'Labor Strike',
  tax_protest:         'Tax Protest',
  manufactured_crisis: 'Manufactured Crisis',
};

export const BATTLE_TYPE_DESCRIPTIONS: Record<BattleCardType, string> = {
  skirmish:            'Single attacker vs unoccupied territory. Auto-resolved.',
  siege:               'Single attacker vs occupied territory.',
  double_siege:        'Multiple attackers vs occupied territory. Defender wins or territory becomes unoccupied.',
  capture_objectives:  'Multiple attackers race to claim an unoccupied territory.',
  bloodbath:           'Mutual attack between two territories. Winner may occupy vacated origin.',
  supply_route_establishment: 'Contest to activate a new supply route.',
  supply_route_race:          'Challenge ownership of an existing supply route.',
  supply_raid:                'Raid enemy territory for stored resources.',
  supply_caravan_escort:      'Protect or intercept a resource shipment in transit.',
  uprising:            'Civil unrest reduces garrison and grants diplomat influence.',
  labor_strike:        'Workers strike at a resource hub, destroying stored resources.',
  tax_protest:         'Challenge opponent\'s gold control. Win to seize gold.',
  manufactured_crisis: 'Engineered conflict. Diplomat-defender wins peacekeeping for influence.',
};

// ─── Helper functions ─────────────────────────────────────────────────────────

export function getBattlePillar(battleType: BattleCardType): BattleCardPillar {
  return BATTLE_TYPE_PILLAR[battleType] ?? 'military';
}

export function getBattleTypeLabel(battleType: BattleCardType): string {
  return BATTLE_TYPE_LABELS[battleType] ?? battleType;
}

export function isNonMilitaryBattleType(battleType: BattleCardType): boolean {
  return BATTLE_TYPE_PILLAR[battleType] !== 'military';
}

export const ALL_MILITARY_TYPES: MilitaryBattleType[] = ['skirmish', 'siege', 'double_siege', 'capture_objectives', 'bloodbath'];
export const ALL_ECONOMIC_TYPES: EconomicBattleType[] = ['supply_route_establishment', 'supply_route_race', 'supply_raid', 'supply_caravan_escort'];
export const ALL_DIPLOMATIC_TYPES: DiplomaticBattleType[] = ['uprising', 'labor_strike', 'tax_protest', 'manufactured_crisis'];
export const ALL_BATTLE_TYPES: BattleCardType[] = [...ALL_MILITARY_TYPES, ...ALL_ECONOMIC_TYPES, ...ALL_DIPLOMATIC_TYPES];

// ─── Lifecycle status ─────────────────────────────────────────────────────────

export type BattleCardStatus =
  | 'pending'           // generated, awaiting tabletop play
  | 'awaiting_result'   // all participants notified, result not yet entered
  | 'active_carryover'  // delayed card reactivated in new round
  | 'pending_approval'  // carryover card with submitted result awaiting sign-off
  | 'result_submitted'  // result entered; awaiting opponent approval
  | 'awaiting_approval' // flagged; opponent not yet approved
  | 'resolved'          // approved and applied to territory/consequence state
  | 'auto_resolved'     // system auto-resolved (timeout / unanimous vote)
  | 'delayed'           // admin marked as delayed; carries over to next round
  | 'forfeited';        // one side forfeited

// ─── Attacker entry ───────────────────────────────────────────────────────────

/**
 * Attacker entry within a BattleCard.
 * Bloodbath cards have entries for BOTH sides — use origin_territory_id to distinguish.
 * Diplomatic/economic cards have a single entry representing the initiating player's force.
 */
export interface BattleCardAttacker {
  player_id: string;
  origin_territory_id: string;
  committed_troops: number;
}

// ─── Main BattleCard interface ────────────────────────────────────────────────

export interface BattleCard {
  id: string;
  campaign_id: string;
  round: number;
  battle_type: BattleCardType;
  battle_pillar?: BattleCardPillar;

  /**
   * Primary contested territory.
   * For bloodbath: one of the two mutual-attack territories.
   * For all others: the territory being attacked or targeted.
   */
  target_territory_id: string;

  /**
   * Defender's CampaignPlayer ID.
   * null for neutral/vacated territories, bloodbath, and some diplomatic cards.
   */
  defender_player_id: string | null;
  defender_troops: number;

  /** All attacking/initiating entries. */
  attackers: BattleCardAttacker[];

  total_attacking_troops: number;
  total_troops_in_battle: number;

  /** scale_factor = total_troops / avg_battle_size (≥1.0) */
  scale_factor: number;
  /** Scaled-down tabletop point total */
  tabletop_size: number;

  status: BattleCardStatus;

  /** true only for bloodbath cards */
  is_mutual: boolean;

  /** Which operation generated this card. 'military_attack' = standard attack phase. */
  battle_card_source?: string;
  /** Player who initiated the operation (may differ from attacker). */
  source_player_id?: string;
  /** Operation-specific stakes metadata used for consequence resolution. */
  source_operation_metadata?: Record<string, unknown>;

  /** battle_preferences: { [player_id]: 'play_tabletop' | 'auto_resolve' | 'delay' | 'forfeit' } */
  battle_preferences?: Record<string, string>;
  voting_closed?: boolean;
  tally_result?: Record<string, unknown>;

  /** Submitted result: { winner_player_id, surviving_tabletop_troops, notes, ... } */
  result?: Record<string, unknown>;
  /** Approval records: { player_id, approved, flagged, at }[] */
  approvals?: Array<Record<string, unknown>>;

  resolved_at?: string;
  result_applied?: boolean;
  created_date?: string;
  updated_date?: string;
}