/**
 * objectiveDefinitions.js — Sprint 4J Objective Catalog v1
 *
 * Single source of truth for all objective card definitions.
 * Used by: ObjectiveCatalog page, ObjectiveCardDisplay, seeding tool.
 *
 * automation_level:
 *   'automatic' — backend can fully evaluate completion.
 *   'assisted'  — backend can identify likely opportunities; player confirms.
 *   'manual'    — admin must confirm; no automated evaluation available.
 *
 * placement_rule:
 *   'captured_territory'              — territory just captured this round.
 *   'structure_territory'             — territory containing the relevant structure.
 *   'primary_contributing_territory'  — main territory involved in the event.
 *   'chosen_territory'                — player selects at completion time.
 *   'affected_region'                 — highest-influence territory in affected region.
 */

export const OBJECTIVE_TIER_REWARDS = { 1: 3, 2: 5, 3: 8, 4: 12 };

export const OBJECTIVE_CATEGORY_CONFIG = {
  military: {
    label: 'Military',
    icon: '⚔️',
    color: 'text-red-400',
    bg: 'bg-red-500/10',
    border: 'border-red-500/30',
    badgeClass: 'bg-red-500/20 text-red-300 border-red-500/40',
  },
  economic: {
    label: 'Economic',
    icon: '💰',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    badgeClass: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/40',
  },
  diplomatic: {
    label: 'Diplomatic',
    icon: '🕊',
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/30',
    badgeClass: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40',
  },
  territorial: {
    label: 'Territorial',
    icon: '🗺',
    color: 'text-green-400',
    bg: 'bg-green-500/10',
    border: 'border-green-500/30',
    badgeClass: 'bg-green-500/20 text-green-300 border-green-500/40',
  },
  infrastructure: {
    label: 'Infrastructure',
    icon: '🏗',
    color: 'text-orange-400',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    badgeClass: 'bg-orange-500/20 text-orange-300 border-orange-500/40',
  },
  manipulation: {
    label: 'Manipulation',
    icon: '🎭',
    color: 'text-purple-400',
    bg: 'bg-purple-500/10',
    border: 'border-purple-500/30',
    badgeClass: 'bg-purple-500/20 text-purple-300 border-purple-500/40',
  },
};

export const TIER_LABELS = { 1: 'I', 2: 'II', 3: 'III', 4: 'IV' };

export const AUTOMATION_LEVEL_CONFIG = {
  automatic: { label: 'Automatic', color: 'text-green-400', badgeClass: 'bg-green-500/15 text-green-300 border-green-500/30' },
  assisted:  { label: 'Assisted',  color: 'text-yellow-400', badgeClass: 'bg-yellow-500/15 text-yellow-300 border-yellow-500/30' },
  manual:    { label: 'Manual',    color: 'text-muted-foreground', badgeClass: 'bg-muted/40 text-muted-foreground border-border' },
};

// ─── Objective Catalog ────────────────────────────────────────────────────────

export const OBJECTIVE_CATALOG = [

  // ── MILITARY ──────────────────────────────────────────────────────────────

  {
    card_id: 'mil_build_barracks',
    category: 'military',
    tier: 1,
    title: 'Construct a Barracks',
    description: 'Build a Barracks building in any territory you control.',
    placement_rule: 'structure_territory',
    automation_level: 'automatic',
    completion_condition: 'build_structure',
    condition_params: { building_type: 'barracks' },
  },
  {
    card_id: 'mil_capture_1',
    category: 'military',
    tier: 1,
    title: 'Capture 1 Territory',
    description: 'Capture at least 1 territory during this round\'s battle phase.',
    placement_rule: 'captured_territory',
    automation_level: 'automatic',
    completion_condition: 'capture_territories',
    condition_params: { count: 1 },
  },
  {
    card_id: 'mil_capture_2',
    category: 'military',
    tier: 2,
    title: 'Capture 2 Territories',
    description: 'Capture at least 2 territories during this round\'s battle phase.',
    placement_rule: 'captured_territory',
    automation_level: 'automatic',
    completion_condition: 'capture_territories',
    condition_params: { count: 2 },
  },
  {
    card_id: 'mil_win_2_battles',
    category: 'military',
    tier: 2,
    title: 'Win 2 Battles',
    description: 'Win at least 2 resolved battles this round.',
    placement_rule: 'primary_contributing_territory',
    automation_level: 'automatic',
    completion_condition: 'win_battles',
    condition_params: { count: 2 },
  },
  {
    card_id: 'mil_flawless_victory',
    category: 'military',
    tier: 3,
    title: 'Flawless Victory',
    description: 'Win a battle without losing a single troop.',
    placement_rule: 'primary_contributing_territory',
    automation_level: 'assisted',
    completion_condition: 'win_battle_no_losses',
    condition_params: {},
  },
  {
    card_id: 'mil_win_siege',
    category: 'military',
    tier: 2,
    title: 'Win a Siege',
    description: 'Win a resolved Siege battle this round.',
    placement_rule: 'captured_territory',
    automation_level: 'automatic',
    completion_condition: 'win_battle_type',
    condition_params: { battle_type: 'siege' },
  },
  {
    card_id: 'mil_win_bloodbath',
    category: 'military',
    tier: 3,
    title: 'Survive the Bloodbath',
    description: 'Win or be the last standing in a Bloodbath battle this round.',
    placement_rule: 'primary_contributing_territory',
    automation_level: 'automatic',
    completion_condition: 'win_battle_type',
    condition_params: { battle_type: 'bloodbath' },
  },
  {
    card_id: 'mil_capture_structured',
    category: 'military',
    tier: 2,
    title: 'Capture a Fortified Territory',
    description: 'Capture a territory that contains at least one active building or structure.',
    placement_rule: 'captured_territory',
    automation_level: 'assisted',
    completion_condition: 'capture_territory_with_structure',
    condition_params: {},
  },
  {
    card_id: 'mil_defend_two',
    category: 'military',
    tier: 3,
    title: 'Hold the Line',
    description: 'Successfully defend against two separate attacks on your territories this round.',
    placement_rule: 'primary_contributing_territory',
    automation_level: 'assisted',
    completion_condition: 'defend_attacks',
    condition_params: { count: 2 },
  },
  {
    card_id: 'mil_largest_army',
    category: 'military',
    tier: 2,
    title: 'Largest Army',
    description: 'Commit the largest total troop count to any single battle this round.',
    placement_rule: 'primary_contributing_territory',
    automation_level: 'assisted',
    completion_condition: 'largest_army_in_battle',
    condition_params: {},
  },

  // ── ECONOMIC ──────────────────────────────────────────────────────────────

  {
    card_id: 'eco_build_marketplace',
    category: 'economic',
    tier: 1,
    title: 'Construct a Marketplace',
    description: 'Build a Marketplace building in any territory you control.',
    placement_rule: 'structure_territory',
    automation_level: 'automatic',
    completion_condition: 'build_structure',
    condition_params: { building_type: 'marketplace' },
  },
  {
    card_id: 'eco_generate_10_gold',
    category: 'economic',
    tier: 2,
    title: 'Gold Rush',
    description: 'Generate at least 10 Gold during a single resource phase.',
    placement_rule: 'chosen_territory',
    automation_level: 'assisted',
    completion_condition: 'generate_resource_amount',
    condition_params: { resource: 'gold', amount: 10 },
  },
  {
    card_id: 'eco_complete_2_builds',
    category: 'economic',
    tier: 2,
    title: 'Master Builder',
    description: 'Complete 2 construction projects in the same round.',
    placement_rule: 'structure_territory',
    automation_level: 'automatic',
    completion_condition: 'complete_construction_projects',
    condition_params: { count: 2 },
  },
  {
    card_id: 'eco_control_3_hubs',
    category: 'economic',
    tier: 3,
    title: 'Industrial Network',
    description: 'Control 3 or more territories with active Resource Hubs.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'control_resource_hubs',
    condition_params: { count: 3 },
  },
  {
    card_id: 'eco_triple_resource',
    category: 'economic',
    tier: 2,
    title: 'Diversified Portfolio',
    description: 'Generate Iron, Timber, and Stone during the same resource phase.',
    placement_rule: 'chosen_territory',
    automation_level: 'assisted',
    completion_condition: 'generate_resource_types',
    condition_params: { types: ['iron', 'timber', 'stone'] },
  },
  {
    card_id: 'eco_control_3_iron',
    category: 'economic',
    tier: 1,
    title: 'Iron Monopoly',
    description: 'Control 3 or more territories that produce Iron.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'control_resource_territories',
    condition_params: { resource: 'iron', count: 3 },
  },
  {
    card_id: 'eco_control_3_timber',
    category: 'economic',
    tier: 1,
    title: 'Timber Monopoly',
    description: 'Control 3 or more territories that produce Timber.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'control_resource_territories',
    condition_params: { resource: 'timber', count: 3 },
  },
  {
    card_id: 'eco_control_3_stone',
    category: 'economic',
    tier: 1,
    title: 'Stone Monopoly',
    description: 'Control 3 or more territories that produce Stone.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'control_resource_territories',
    condition_params: { resource: 'stone', count: 3 },
  },
  {
    card_id: 'eco_most_gold',
    category: 'economic',
    tier: 3,
    title: 'Wealthiest Nation',
    description: 'Generate more Gold than any other player during a single resource phase.',
    placement_rule: 'chosen_territory',
    automation_level: 'assisted',
    completion_condition: 'generate_most_resource',
    condition_params: { resource: 'gold' },
  },
  {
    card_id: 'eco_profit_loan',
    category: 'economic',
    tier: 2,
    title: 'Turn a Profit',
    description: 'Gain Gold from a loan or trade agreement this round.',
    placement_rule: 'chosen_territory',
    automation_level: 'manual',
    completion_condition: null,
    condition_params: {},
  },

  // ── DIPLOMATIC ────────────────────────────────────────────────────────────

  {
    card_id: 'dip_build_embassy',
    category: 'diplomatic',
    tier: 1,
    title: 'Establish an Embassy',
    description: 'Build an Embassy building in any territory you control.',
    placement_rule: 'structure_territory',
    automation_level: 'automatic',
    completion_condition: 'build_structure',
    condition_params: { building_type: 'embassy' },
  },
  {
    card_id: 'dip_broker_trade',
    category: 'diplomatic',
    tier: 2,
    title: 'Broker a Trade Agreement',
    description: 'Successfully submit a Merchant Convoy or Non-Aggression Pact diplomatic action.',
    placement_rule: 'affected_region',
    automation_level: 'automatic',
    completion_condition: 'submit_diplomatic_action',
    condition_params: { action_types: ['merchant_convoy', 'non_aggression_pact'] },
  },
  {
    card_id: 'dip_two_regions',
    category: 'diplomatic',
    tier: 1,
    title: 'Spreading Influence',
    description: 'Hold permanent influence in at least 2 different regions simultaneously.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'hold_influence_in_regions',
    condition_params: { count: 2 },
  },
  {
    card_id: 'dip_no_territory_region',
    category: 'diplomatic',
    tier: 3,
    title: 'Shadow Presence',
    description: 'Hold influence in a region where you control no territories.',
    placement_rule: 'affected_region',
    automation_level: 'automatic',
    completion_condition: 'influence_without_territory',
    condition_params: {},
  },
  {
    card_id: 'dip_most_influence',
    category: 'diplomatic',
    tier: 3,
    title: 'Voice of Authority',
    description: 'Generate more total influence than any other player this round.',
    placement_rule: 'chosen_territory',
    automation_level: 'assisted',
    completion_condition: 'generate_most_influence',
    condition_params: {},
  },
  {
    card_id: 'dip_rival_region',
    category: 'diplomatic',
    tier: 2,
    title: 'Undermine the Powerful',
    description: 'Gain permanent influence in a region currently controlled by another player.',
    placement_rule: 'affected_region',
    automation_level: 'automatic',
    completion_condition: 'influence_in_controlled_region',
    condition_params: {},
  },
  {
    card_id: 'dip_3_diplomatic_structures',
    category: 'diplomatic',
    tier: 3,
    title: 'Diplomatic Corps',
    description: 'Control 3 or more active diplomatic buildings (Embassy, Council Chamber, or Foreign Office).',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'control_pillar_structures',
    condition_params: { pillar: 'diplomatic', count: 3 },
  },
  {
    card_id: 'dip_no_battle',
    category: 'diplomatic',
    tier: 2,
    title: 'Peaceful Expansion',
    description: 'Gain permanent influence in a territory without winning or initiating any battle this round.',
    placement_rule: 'chosen_territory',
    automation_level: 'assisted',
    completion_condition: 'gain_influence_without_battle',
    condition_params: {},
  },
  {
    card_id: 'dip_no_battle_region',
    category: 'diplomatic',
    tier: 2,
    title: 'Sanctuary',
    description: 'Generate influence in a region where no battles occurred this round.',
    placement_rule: 'affected_region',
    automation_level: 'assisted',
    completion_condition: 'influence_in_peaceful_region',
    condition_params: {},
  },
  {
    card_id: 'dip_most_regions',
    category: 'diplomatic',
    tier: 4,
    title: 'Omnipresent',
    description: 'Hold influence in more regions than any other player.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'influence_in_most_regions',
    condition_params: {},
  },

  // ── TERRITORIAL ───────────────────────────────────────────────────────────

  {
    card_id: 'ter_occupy_x',
    category: 'territorial',
    tier: 2,
    title: 'Territorial Expansion',
    description: 'Occupy at least 8 territories simultaneously at any point this round.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'occupy_territories',
    condition_params: { count: 8 },
  },
  {
    card_id: 'ter_occupy_region',
    category: 'territorial',
    tier: 3,
    title: 'Regional Dominance',
    description: 'Occupy every territory in at least one region.',
    placement_rule: 'affected_region',
    automation_level: 'automatic',
    completion_condition: 'occupy_full_region',
    condition_params: {},
  },
  {
    card_id: 'ter_occupy_continent',
    category: 'territorial',
    tier: 4,
    title: 'Continental Control',
    description: 'Occupy every territory on at least one continent.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'occupy_full_continent',
    condition_params: {},
  },
  {
    card_id: 'ter_new_region',
    category: 'territorial',
    tier: 1,
    title: 'Beachhead',
    description: 'Capture a territory in a region you did not occupy at the start of this round.',
    placement_rule: 'captured_territory',
    automation_level: 'automatic',
    completion_condition: 'capture_in_new_region',
    condition_params: {},
  },
  {
    card_id: 'ter_4_regions',
    category: 'territorial',
    tier: 2,
    title: 'Far-Reaching Empire',
    description: 'Control territories in 4 or more different regions simultaneously.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'occupy_regions',
    condition_params: { count: 4 },
  },
  {
    card_id: 'ter_every_continent',
    category: 'territorial',
    tier: 3,
    title: 'World Stage',
    description: 'Control at least one territory on every continent.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'territory_on_every_continent',
    condition_params: {},
  },
  {
    card_id: 'ter_grow_by_2',
    category: 'territorial',
    tier: 1,
    title: 'Forward March',
    description: 'Increase your territory count by at least 2 this round.',
    placement_rule: 'captured_territory',
    automation_level: 'automatic',
    completion_condition: 'increase_territory_count',
    condition_params: { count: 2 },
  },
  {
    card_id: 'ter_hold_all',
    category: 'territorial',
    tier: 2,
    title: 'Iron Grip',
    description: 'End the round owning every territory you held at the start of the round.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'maintain_all_territories',
    condition_params: {},
  },
  {
    card_id: 'ter_unoccupied',
    category: 'territorial',
    tier: 1,
    title: 'Manifest Destiny',
    description: 'Take control of at least one previously unoccupied territory this round.',
    placement_rule: 'captured_territory',
    automation_level: 'automatic',
    completion_condition: 'capture_unoccupied',
    condition_params: {},
  },
  {
    card_id: 'ter_surround_enemy',
    category: 'territorial',
    tier: 3,
    title: 'Encirclement',
    description: 'Control every territory adjacent to at least one enemy-held territory.',
    placement_rule: 'chosen_territory',
    automation_level: 'assisted',
    completion_condition: 'surround_territory',
    condition_params: {},
  },

  // ── INFRASTRUCTURE ────────────────────────────────────────────────────────

  {
    card_id: 'inf_build_military',
    category: 'infrastructure',
    tier: 1,
    title: 'Military Construction',
    description: 'Complete construction of any military pillar building.',
    placement_rule: 'structure_territory',
    automation_level: 'automatic',
    completion_condition: 'complete_pillar_build',
    condition_params: { pillar: 'military' },
  },
  {
    card_id: 'inf_build_economic',
    category: 'infrastructure',
    tier: 1,
    title: 'Economic Construction',
    description: 'Complete construction of any economic pillar building.',
    placement_rule: 'structure_territory',
    automation_level: 'automatic',
    completion_condition: 'complete_pillar_build',
    condition_params: { pillar: 'economic' },
  },
  {
    card_id: 'inf_build_diplomatic',
    category: 'infrastructure',
    tier: 1,
    title: 'Diplomatic Construction',
    description: 'Complete construction of any diplomatic pillar building.',
    placement_rule: 'structure_territory',
    automation_level: 'automatic',
    completion_condition: 'complete_pillar_build',
    condition_params: { pillar: 'diplomatic' },
  },
  {
    card_id: 'inf_control_5_structures',
    category: 'infrastructure',
    tier: 3,
    title: 'Fortified Nation',
    description: 'Control 5 or more active buildings across all your territories.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'control_active_buildings',
    condition_params: { count: 5 },
  },
  {
    card_id: 'inf_3_regions',
    category: 'infrastructure',
    tier: 3,
    title: 'Distributed Power',
    description: 'Construct a building in 3 different regions.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'build_in_regions',
    condition_params: { count: 3 },
  },
  {
    card_id: 'inf_multi_structure',
    category: 'infrastructure',
    tier: 2,
    title: 'Fortified Stronghold',
    description: 'Control a territory with 2 or more active buildings.',
    placement_rule: 'structure_territory',
    automation_level: 'automatic',
    completion_condition: 'multi_structure_territory',
    condition_params: { count: 2 },
  },
  {
    card_id: 'inf_maintain_all',
    category: 'infrastructure',
    tier: 2,
    title: 'Upkeep Mastery',
    description: 'End the round with all your buildings still active (none destroyed or damaged).',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'maintain_all_buildings',
    condition_params: {},
  },
  {
    card_id: 'inf_build_port',
    category: 'infrastructure',
    tier: 2,
    title: 'Construct a Port',
    description: 'Build any building in a coastal territory.',
    placement_rule: 'structure_territory',
    automation_level: 'assisted',
    completion_condition: 'build_in_coastal',
    condition_params: {},
  },
  {
    card_id: 'inf_build_railway',
    category: 'infrastructure',
    tier: 2,
    title: 'Lay a Railway',
    description: 'Establish an active supply route connecting 3 or more territories.',
    placement_rule: 'chosen_territory',
    automation_level: 'automatic',
    completion_condition: 'establish_supply_route_length',
    condition_params: { length: 3 },
  },
  {
    card_id: 'inf_upgrade_structure',
    category: 'infrastructure',
    tier: 2,
    title: 'Upgrade an Existing Structure',
    description: 'Build a second building in a territory that already has an active building.',
    placement_rule: 'structure_territory',
    automation_level: 'automatic',
    completion_condition: 'build_in_occupied_territory',
    condition_params: {},
  },

  // ── MANIPULATION ──────────────────────────────────────────────────────────

  {
    card_id: 'man_sway_battle',
    category: 'manipulation',
    tier: 3,
    title: 'The Power Behind the Throne',
    description: 'Successfully use a diplomatic action that directly alters the outcome of a battle.',
    placement_rule: 'affected_region',
    automation_level: 'manual',
    completion_condition: null,
    condition_params: {},
  },
  {
    card_id: 'man_prevent_attack',
    category: 'manipulation',
    tier: 3,
    title: 'Deterrence',
    description: 'Use influence to prevent an attack on a territory you do not own.',
    placement_rule: 'affected_region',
    automation_level: 'manual',
    completion_condition: null,
    condition_params: {},
  },
  {
    card_id: 'man_help_objective',
    category: 'manipulation',
    tier: 2,
    title: 'Allied Interest',
    description: 'Take an action that directly enables another player to complete one of their objectives.',
    placement_rule: 'chosen_territory',
    automation_level: 'manual',
    completion_condition: null,
    condition_params: {},
  },
  {
    card_id: 'man_cause_battle',
    category: 'manipulation',
    tier: 3,
    title: 'War Profiteer',
    description: 'Cause two opposing players to enter into a battle against each other.',
    placement_rule: 'affected_region',
    automation_level: 'manual',
    completion_condition: null,
    condition_params: {},
  },
  {
    card_id: 'man_influence_from_battle',
    category: 'manipulation',
    tier: 2,
    title: 'Opportunist',
    description: 'Gain influence from a battle you were not a participant in.',
    placement_rule: 'affected_region',
    automation_level: 'assisted',
    completion_condition: 'influence_from_others_battle',
    condition_params: {},
  },
  {
    card_id: 'man_cause_resource_loss',
    category: 'manipulation',
    tier: 3,
    title: 'Economic Sabotage',
    description: 'Cause another player to lose Gold or resources through a diplomatic or military action.',
    placement_rule: 'affected_region',
    automation_level: 'manual',
    completion_condition: null,
    condition_params: {},
  },
  {
    card_id: 'man_alter_battle_setup',
    category: 'manipulation',
    tier: 3,
    title: 'The Hidden Hand',
    description: 'Use influence to alter the setup or troop composition of a battle you are not leading.',
    placement_rule: 'affected_region',
    automation_level: 'manual',
    completion_condition: null,
    condition_params: {},
  },
  {
    card_id: 'man_mercenary',
    category: 'manipulation',
    tier: 2,
    title: 'Fund a Mercenary',
    description: 'Spend resources or influence to fund a mercenary action benefiting another player\'s battle.',
    placement_rule: 'affected_region',
    automation_level: 'manual',
    completion_condition: null,
    condition_params: {},
  },
  {
    card_id: 'man_end_treaty',
    category: 'manipulation',
    tier: 3,
    title: 'Treaty Breaker',
    description: 'Cause an existing treaty or non-aggression pact between two other players to end prematurely.',
    placement_rule: 'affected_region',
    automation_level: 'manual',
    completion_condition: null,
    condition_params: {},
  },
  {
    card_id: 'man_decrease_production',
    category: 'manipulation',
    tier: 3,
    title: 'Supply Disruption',
    description: 'Cause another player\'s resource production to decrease through disruption of supply routes or territories.',
    placement_rule: 'affected_region',
    automation_level: 'manual',
    completion_condition: null,
    condition_params: {},
  },
];

// Lookup by card_id for O(1) access
export const OBJECTIVE_BY_ID = Object.fromEntries(
  OBJECTIVE_CATALOG.map(obj => [obj.card_id, obj])
);

// Grouped by category
export const OBJECTIVES_BY_CATEGORY = OBJECTIVE_CATALOG.reduce((acc, obj) => {
  if (!acc[obj.category]) acc[obj.category] = [];
  acc[obj.category].push(obj);
  return acc;
}, {});

export const CATEGORY_ORDER = ['military', 'economic', 'diplomatic', 'territorial', 'infrastructure', 'manipulation'];